### ISSUE TITLE
配置好相关环境后运行main.js出现语法错误

### ISSUE THREAD

**Issue by Ziyang-Bai** [CrosSt-Chat/CSC-main#3]
配置好相关环境后运行main.js出现语法错误
azureuser@1c1g:~/CSC-main-main$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN csc-main@0.1.0 license should be a valid SPDX license expression

added 1 package from 1 contributor and audited 1 package in 0.271s
found 0 vulnerabilities

azureuser@1c1g:~/CSC-main-main$ node main.js
file:///home/azureuser/CSC-main-main/hazel/module-loader.js:2
import { cpSync, mkdirSync, rmSync } from 'node:fs';
         ^^^^^^
SyntaxError: The requested module 'node:fs' does not provide an export named 'cpSync'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)

**Comment by Henrize** [comment]
请升级到最新 LTS 版本运行十字街客户端，或者提供出现该问题的 Node.js 版本号。
